# dashing/ros-distro-preferred-providers.inc
#
# Copyright (c) 2019 LG Electronics, Inc.

# Set PREFERRED_PROVIDER_<PN> here for non-platform packages and to override those set in
# ros-distro-platform-preferred-providers.inc .

# PREFERRED_PROVIDER_libyaml = "ros2-libyaml-vendor"
# PREFERRED_PROVIDER_libyaml-dev = "ros2-libyaml-vendor-dev"
# PREFERRED_PROVIDER_libyaml-dbg = "ros2-libyaml-vendor-dbg"
